# Generated by Django 5.2.7 on 2025-10-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('portfolio', models.CharField(choices=[('PHRONESIS', 'Phronesis (Passif)'), ('FLAGSHIP', 'FlagShip (Actif)')], max_length=20)),
                ('sector', models.CharField(default='Technology', max_length=50)),
                ('asset_type', models.CharField(default='stock', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('total_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invested_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('shares', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20)),
                ('profile_type', models.CharField(default='Standard', max_length=50)),
                ('avatar', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PHRONESIS', 'Phronesis (Passif)'), ('FLAGSHIP', 'FlagShip (Actif)')], max_length=20, unique=True)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('BUY', 'Achat'), ('SELL', 'Vente'), ('DIVIDEND', 'Dividende'), ('INTEREST', 'Intérêt')], max_length=20)),
                ('date', models.DateField()),
                ('portfolio', models.CharField(choices=[('PHRONESIS', 'Phronesis (Passif)'), ('FLAGSHIP', 'FlagShip (Actif)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('asset', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('member_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
