# Generated by Django 5.2.7 on 2025-11-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstment', '0003_remove_compte_member_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USDTWalletConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('TRC20', 'USDT Tron (TRC-20)'), ('ERC20', 'USDT Ethereum (ERC-20)'), ('BEP20', 'USDT BSC (BEP-20)')], max_length=10, unique=True)),
                ('deposit_address', models.CharField(max_length=100)),
                ('private_key', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='USDTPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('DEPOSIT', 'Dépôt USDT'), ('WITHDRAWAL', 'Retrait USDT')], max_length=20)),
                ('amount_usdt', models.DecimalField(decimal_places=6, max_digits=20)),
                ('network', models.CharField(choices=[('TRC20', 'USDT Tron (TRC-20)'), ('ERC20', 'USDT Ethereum (ERC-20)'), ('BEP20', 'USDT BSC (BEP-20)')], default='TRC20', max_length=10)),
                ('wallet_address', models.CharField(max_length=100)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('portfolio', models.CharField(choices=[('PHRONESIS', 'Phronesis (Passif)'), ('FLAGSHIP', 'FlagShip (Actif)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usdt_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
