# Generated by Django 5.2.7 on 2025-11-13 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstment', '0003_add_owner_is_public_to_holding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holding',
            name='portfolio',
            field=models.CharField(choices=[('PHRONESIS', 'Phronesis (Passif)'), ('FLAGSHIP', 'FlagShip (Actif)')], max_length=20),
        ),
    ]
