# Generated by Django 5.2.7 on 2025-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstment', '0004_usdtwalletconfig_usdtpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usdtpayment',
            old_name='created_at',
            new_name='paid_at',
        ),
        migrations.AddField(
            model_name='usdtpayment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usdtpayment',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usdtpayment',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='usdtpayment',
            name='sender_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usdtpayment',
            name='confirmed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usdtpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('EXPIRED', 'Expiré'), ('FAILED', 'Échoué')], default='PENDING', max_length=20),
        ),
    ]
