# Generated by Django 5.2.7 on 2025-12-01 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstment', '0005_rename_created_at_usdtpayment_paid_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_block', models.BigIntegerField(default=0)),
                ('network', models.CharField(default='TRC20', max_length=10)),
                ('last_check_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWalletConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='TRC20', max_length=10, unique=True)),
                ('wallet_address', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='usdtpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 1, 16, 11, 11, 850062, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usdtpayment',
            name='transaction_id',
            field=models.CharField(default='USDT-DEFAULT', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usdtpayment',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 16, 27, 53, 137045, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usdtpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
