# Generated by Django 5.2.7 on 2025-12-12 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstment', '0006_blockchainmonitoring_cryptowalletconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('fedapay_transction_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('payement_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('orange', 'Orange Money')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('DECLINED', 'Refusé'), ('CANCELED', 'Annulé')], default='PENDING', max_length=20)),
                ('portfolio', models.CharField(choices=[('PHRONESIS', 'Phronesis (Passif)'), ('FLAGSHIP', 'FlagShip (Actif)')], max_length=20)),
                ('is_activated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fedapay_reference', models.CharField(blank=True, max_length=100)),
                ('callback_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
