# Generated by Django 5.2.7 on 2025-12-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inverstment', '0007_mobilemoneypayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilemoneypayment',
            old_name='payement_method',
            new_name='payment_method',
        ),
    ]
