# Generated by Django 5.1.7 on 2026-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstment', '0008_rename_payement_method_mobilemoneypayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte_member',
            name='gross_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='compte_member',
            name='member_external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='compte_member',
            name='shares_count',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
