# Generated by Django 5.1.7 on 2026-03-28 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstment', '0009_compte_member_gross_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(default='Phronesis', max_length=100)),
                ('semaine', models.CharField(blank=True, max_length=50)),
                ('vnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.CharField(max_length=200)),
                ('poids', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('quantite', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('cours_achat', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cours_cloture', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dividende', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rendement_brut', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('investissement', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('valorisation', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rendement_annuel', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('variation_semaine', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='inverstment.portfoliosnapshot')),
            ],
        ),
    ]
