# Generated by Django 5.1.7 on 2026-04-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstment', '0012_ticker_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerasset',
            name='currency',
            field=models.CharField(default='USD', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickerasset',
            name='current_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
