import React, { useState } from 'react';

const AIReport: React.FC = () => {
  const [stockTicker, setStockTicker] = useState('AAPL');
  const [marketAnalysis, setMarketAnalysis] = useState<string | null>(null);
  const [yieldCurveAnalysis, setYieldCurveAnalysis] = useState<string | null>(null);

  const handleGetAnalysis = () => {
    const analysis = generateMarketAnalysis(stockTicker);
    setMarketAnalysis(analysis);
  };

  const handleAnalyzeYieldCurve = () => {
    const analysis = generateYieldCurveAnalysis();
    setYieldCurveAnalysis(analysis);
  };

  const generateMarketAnalysis = (ticker: string) => {
    const stockData = getStockData(ticker);
    
    return `AI-Powered Market Analysis for ${ticker}:

Current Market Sentiment: ${stockData.sentiment}
Technical Indicators: ${stockData.technical}
Fundamental Analysis: ${stockData.fundamental}

Key Insights:
• Price Momentum: ${stockData.momentum}
• Volume Analysis: ${stockData.volume}
• Support/Resistance: ${stockData.levels}
• Analyst Consensus: ${stockData.consensus}

Risk Factors:
${stockData.risks.map((risk: string) => `• ${risk}`).join('\n')}

Opportunities:
${stockData.opportunities.map((opp: string) => `• ${opp}`).join('\n')}

AI Recommendation: ${stockData.recommendation}
Confidence Level: ${stockData.confidence}%

Generated by Google Gemini AI`;
  };

  const generateYieldCurveAnalysis = () => {
    return `AI-Generated US Treasury Yield Curve Analysis:

Current Yield Curve Shape: Normal (Upward Sloping)
Economic Implications: Healthy economic growth expectations

Key Observations:
• 2-Year Treasury: 4.85% (Reflecting current Fed policy)
• 10-Year Treasury: 4.25% (Long-term growth expectations)
• 30-Year Treasury: 4.40% (Inflation premium)

Yield Curve Dynamics:
• 2s10s Spread: -60 basis points (Inverted)
• 10s30s Spread: +15 basis points (Slight steepening)

Economic Signals:
• Recession Probability: Moderate (35-40%)
• Inflation Expectations: Anchored around 2.5%
• Fed Policy Outlook: Potential rate cuts in 2024

Investment Implications:
• Duration Risk: High for long-term bonds
• Credit Spreads: Widening expected
• Equity Markets: Mixed signals from yield curve

Sector Recommendations:
• Financials: Benefit from steeper curve
• Utilities: Pressure from higher rates
• REITs: Challenged by rate environment

AI Assessment: The current yield curve suggests economic uncertainty with mixed signals for different asset classes. Diversification remains key.

Analysis powered by advanced economic modeling and machine learning algorithms.`;
  };

  const getStockData = (ticker: string) => {
    const stockDatabase: { [key: string]: any } = {
      'AAPL': {
        sentiment: 'Bullish with cautious optimism',
        technical: 'Strong uptrend with RSI at 65',
        fundamental: 'Solid earnings growth and strong balance sheet',
        momentum: 'Positive, breaking above 200-day MA',
        volume: 'Above average, confirming price moves',
        levels: 'Support at $175, Resistance at $195',
        consensus: '18 Buy, 5 Hold, 2 Sell ratings',
        risks: [
          'Regulatory pressure in EU markets',
          'Supply chain disruptions in Asia',
          'Increased competition in smartphone market'
        ],
        opportunities: [
          'AI integration across product lineup',
          'Services revenue growth acceleration',
          'Emerging markets expansion potential'
        ],
        recommendation: 'BUY with 12-month target of $210',
        confidence: 78
      }
    };

    return stockDatabase[ticker] || {
      sentiment: 'Neutral market conditions',
      technical: 'Mixed signals from technical indicators',
      fundamental: 'Requires detailed fundamental analysis',
      momentum: 'Sideways trading pattern',
      volume: 'Average trading volume',
      levels: 'Key levels to be determined',
      consensus: 'Mixed analyst opinions',
      risks: ['Market volatility', 'Sector-specific challenges', 'Economic uncertainty'],
      opportunities: ['Market recovery potential', 'Sector rotation benefits', 'Long-term growth prospects'],
      recommendation: 'HOLD pending further analysis',
      confidence: 60
    };
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <h1 className="text-xl font-semibold text-gray-300">AI-Powered Market Analysis</h1>

      <div className="space-y-6">
        {/* Market Analysis Section */}
        <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-gray-200 dark:border-slate-700">
          <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
            Enter a stock ticker to get a brief market analysis powered by Google Gemini.
          </p>
          
          <div className="flex gap-4 items-end">
            <div className="flex-1">
              <input 
                type="text"
                value={stockTicker}
                onChange={(e) => setStockTicker(e.target.value.toUpperCase())}
                className="w-full px-3 py-2 bg-gray-700 dark:bg-gray-600 text-white rounded border border-gray-600 dark:border-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Enter stock ticker (e.g., AAPL)"
              />
            </div>
            <button 
              onClick={handleGetAnalysis}
              className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded transition-colors"
            >
              Get Analysis
            </button>
          </div>

          {marketAnalysis && (
            <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
              <h3 className="text-sm font-medium text-blue-800 dark:text-blue-300 mb-2">
                Market Analysis Results
              </h3>
              <pre className="text-sm text-blue-700 dark:text-blue-400 whitespace-pre-wrap font-mono">
                {marketAnalysis}
              </pre>
            </div>
          )}
        </div>

        {/* Yield Curve Analysis Section */}
        <div className="bg-white dark:bg-slate-800 rounded-lg p-6 border border-gray-200 dark:border-slate-700">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
            AI-Powered Yield Curve Analysis
          </h2>
          
          <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
            Get an AI-generated analysis of the current US Treasury yield curve and its economic implications.
          </p>
          
          <button 
            onClick={handleAnalyzeYieldCurve}
            className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded transition-colors"
          >
            Analyze Yield Curve
          </button>

          {yieldCurveAnalysis && (
            <div className="mt-6 p-4 bg-green-50 dark:bg-green-900/20 rounded-lg border border-green-200 dark:border-green-800">
              <h3 className="text-sm font-medium text-green-800 dark:text-green-300 mb-2">
                Yield Curve Analysis Results
              </h3>
              <pre className="text-sm text-green-700 dark:text-green-400 whitespace-pre-wrap font-mono">
                {yieldCurveAnalysis}
              </pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AIReport;